export const PERMISSION = {
  SUPER_USER: 'PM_SUPER_USER',
  MODULE: {
    BASIC: 'PM_MODULE_BASIC',
    CREATE: 'PM_MODULE_CREATE',
    DETAIL: 'PM_MODULE_DETAIL',
    EDIT: 'PM_MODULE_EDIT',
    DELETE: 'PM_MODULE_DELETE',
  },
  PACKAGE: {
    BASIC: 'PM_PACKAGE_BASIC',
    CREATE: 'PM_PACKAGE_CREATE',
    DETAIL: 'PM_PACKAGE_DETAIL',
    EDIT: 'PM_PACKAGE_EDIT',
    DELETE: 'PM_PACKAGE_DELETE',
  },
  ORGANIZATION: {
    BASIC: 'PM_ORGANIZATION_BASIC',
    CREATE: 'PM_ORGANIZATION_CREATE',
    DETAIL: 'PM_ORGANIZATION_DETAIL',
    EDIT: 'PM_ORGANIZATION_EDIT',
    DELETE: 'PM_ORGANIZATION_DELETE',
  },
  ORGANIZATION_ROLE: {
    BASIC: 'PM_ORGANIZATION_ROLE_BASIC',
    CREATE: 'PM_ORGANIZATION_ROLE_CREATE',
    DETAIL: 'PM_ORGANIZATION_ROLE_DETAIL',
    EDIT: 'PM_ORGANIZATION_ROLE_EDIT',
    DELETE: 'PM_ORGANIZATION_ROLE_DELETE',
  },
  USER: {
    BASIC: 'PM_USER_BASIC',
    CREATE: 'PM_USER_CREATE',
    DETAIL: 'PM_USER_DETAIL',
    EDIT: 'PM_USER_EDIT',
    DELETE: 'PM_USER_DELETE',
  },
};
