export const PERMISSION = {
  MODULE: {
    BASIC: 'PM_MODULE_BASIC',
    CREATE: 'PM_MODULE_CREATE',
    DETAIL: 'PM_MODULE_DETAIL',
    EDIT: 'PM_MODULE_EDIT',
    DELETE: 'PM_MODULE_DELETE',
  },
  PACKAGE: {
    BASIC: 'PM_PACKAGE_BASIC',
    CREATE: 'PM_PACKAGE_CREATE',
    DETAIL: 'PM_PACKAGE_DETAIL',
    EDIT: 'PM_PACKAGE_EDIT',
    DELETE: 'PM_PACKAGE_DELETE',
  },
};
